### ISSUE TITLE
Generic chunk type 0x0011 (Correlation ID) is mandatory

### ISSUE THREAD

**Issue by ivlovric** [sipcapture/HEP#7]
Hi sipcapture team,

We noticed that HEP parsers and decoders (heplify-server as one) need HEP "Correlation ID" chunk of type 0x0011 ("Internal correlation id" in specification doc) to properly parse and decode HEP packet which is not stated or obvious in document nor given example.

If this makes sense, please update given protocol specification :)

Thanks and regards,
I

**Comment by lmangani** [comment]
Good point @ivlovric 
Populating a correlation_id header should not really a requirement in terms of HEP per-se but as you correctly noticed, it is indeed a requirement for it to be present in our implementations for certain protocol types. Could you confirm if the empty header alone passes the test?

**Comment by ivlovric** [comment]
Hi Lorenzo,
I am confirming that empty encoded correlation_id/chunk type 0x0011 is **not importing** by neither picserver and heplify-server thus failing this test. I tried with message type JSON/QOS/34 but somehow assume that other message types will not change this behavior.

Thanks,
I

**Comment by lmangani** [comment]
@ivlovric this actually makes sense if you were talking about events since all "non-session" ids such as TYPE 100 mandate a correlation header present in order to be pointed to the parent. Without it they become literally unlinked nodes in the database only available for direct search, which is not the usecase for the vast majority of deployments.

How would your usecase work without a correlation_header set? (feel free to share this internally if sensitive)

**Comment by ivlovric** [comment]
All clear now. We want things to be correlated but we were sending correlation id in rtp report payload itself and somehow expected that to be enough and for decoders to import such packets to database. But as you pointed out this is not fully protocol related per-se but way that parsers and decoders choose to work with given protocol. 
We were using packet example from this document and expected that to work without any further research. :)

Thanks for all the clarifications.
